version: '3.9'

services:
  nuxt:
    container_name: nuxt
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/app:cached
      - nuxt_node_modules:/app/node_modules
    ports:
      - "3000:3000"
      - "24678:24678"
    tty: true
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - NUXT_FACE_ENDPOINT=${NUXT_FACE_ENDPOINT}
      - NUXT_FACE_API_KEY=${NUXT_FACE_API_KEY}
    command: npm run dev
    env_file:
      - .env

volumes:
  nuxt_node_modules:
